### ISSUE TITLE
SmartRename not doing anything

### ISSUE THREAD

**Issue by Zhiro90** [chrdavis/SmartRename#8] opened 2020-08-12 13:55 UTC
Tried both versions (32 and 64 bit). Windows 7x64. After a task is issued, the window closes and nothing happens. The folder is unprotected and the filenames are not very long. Any idea why?

**Comment by chrdavis** [comment] 2020-08-14 17:28
I can repro this when performing renames on items from OneDrive.  Looks like my recent fix to allow OneDrive items led to this.  Can you verify it repros on OneDrive items and not on local files?

**Comment by Zhiro90** [comment] 2020-08-14 20:43
> I can repro this when performing renames on items from OneDrive. Looks like my recent fix to allow OneDrive items led to this. Can you verify it repros on OneDrive items and not on local files?

I don't use OneDrive but i can install it to try this. Can you give me the steps on what to do exactly with OneDrive?

**Comment by chrdavis** [comment] 2020-08-14 20:44
What is the path to the files/folders you are renaming?  What options did you have set?

**Comment by Zhiro90** [comment] 2020-08-14 21:13
here's a quick recording with the info you asked for https://dump.video/IzjwDT

**Comment by chrdavis** [comment] 2020-08-14 21:16
Thanks.  Are you using some sort of Shell replacement for Windows Explorer?

**Comment by Zhiro90** [comment] 2020-08-14 21:19
a custom theme (placebo for windows 7 https://www.deviantart.com/solmiler/art/Placebo-for-Windows-7-188414149) and Qtabbar for tabs

**Comment by chrdavis** [comment] 2020-08-14 21:23
OK, let me install a Win7 VM to see if I can reproduce the issue there.

**Comment by chrdavis** [comment] 2020-08-15 04:40
I can reproduce the issue on Win7.  I'm pretty sure I know what is wrong.  I'll code up a fix.  Thanks.

**Comment by chrdavis** [comment] 2020-08-15 06:33
Fixed in latest release.  Thanks for reporting this.

**Closed by chrdavis** 2020-08-15 06:33 UTC
